CI/CD. One more experiment with separate tests job.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -63,19 +63,44 @@ jobs:
         # -Dsonar.dynamicAnalysis=reuseReports
         # Checks-out your greencity.repository under $GITHUB_WORKSPACE, so your job can access it
 
-      - name: Test Reporter
-        uses: dorny/test-reporter@v1
-        if: success() || failure()
+#      - name: Test Reporter
+#        uses: dorny/test-reporter@v1
+#        if: success() || failure()
+#        with:
+#          name: Tests Report
+#          path: ${{ env.userRepoName }}/target/surefire-reports/*.xml
+#          reporter: java-junit
+      - name: Upload test reports
+        if: always()
+        uses: actions/upload-artifact@v4
         with:
-          name: Tests Report
+          name: test-reports
           path: ${{ env.userRepoName }}/target/surefire-reports/*.xml
-          reporter: java-junit
+          if-no-files-found: warn
 
       - name: Rename user jar to app
         run: mv $userRepoName/target/*.jar $userRepoName/target/$onbootJarName
 
       - name: Set outputs
         run: echo "GITHUB_SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
+
+  test-report:
+    runs-on: ubuntu-latest
+    needs: build
+    if: ${{ always() }}   # щоб job спробував працювати навіть якщо build провалився
+    steps:
+      - name: Download test reports
+        uses: actions/download-artifact@v5
+        with:
+          name: test-reports
+          path: ./reports
+
+      - name: Test Reporter
+        uses: dorny/test-reporter@v2
+        with:
+          name: Tests Report
+          path: ./reports/*.xml
+          reporter: java-junit
 
   docker-build:
     runs-on: ubuntu-latest
